language: node_js
node_js:
  - 4
  - 6
  - 8
sudo: required
before_install:
  - sudo apt-get update
  - sudo apt-get install --assume-yes apache2-utils
  - npm install -g npm@3.10.8
  - npm install -g grunt-cli
install: npm install
script:
  - grunt
  
