language: node_js
node_js:
  - 6
  - 8
  - 10
sudo: required
before_install:
  - sudo apt-get update
  - sudo apt-get install --assume-yes apache2-utils
  - npm install -g grunt-cli
install: npm install
script:
  - grunt

